"""
Transforms nodes aggregation.
"""

from .transform import TransformMeshNode, NODE_CLASS_MAPPINGS as TRANSFORM_MAPS, NODE_DISPLAY_NAME_MAPPINGS as TRANSFORM_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(TRANSFORM_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(TRANSFORM_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
