# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Visualization nodes aggregation.
"""

from .preview_mesh import PreviewMeshNode, NODE_CLASS_MAPPINGS as PREVIEW_MESH_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_MESH_DISP
from .preview_mesh_vtk import PreviewMeshVTKNode, NODE_CLASS_MAPPINGS as PREVIEW_MESH_VTK_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_MESH_VTK_DISP
from .preview_mesh_vtk_batch import PreviewMeshVTKBatchNode, NODE_CLASS_MAPPINGS as PREVIEW_MESH_VTK_BATCH_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_MESH_VTK_BATCH_DISP
from .preview_mesh_dual import PreviewMeshDualNode, NODE_CLASS_MAPPINGS as PREVIEW_MESH_DUAL_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_MESH_DUAL_DISP
from .preview_mesh_uv import PreviewMeshUVNode, NODE_CLASS_MAPPINGS as PREVIEW_MESH_UV_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_MESH_UV_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(PREVIEW_MESH_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(PREVIEW_MESH_DISP)
NODE_CLASS_MAPPINGS.update(PREVIEW_MESH_VTK_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(PREVIEW_MESH_VTK_DISP)
NODE_CLASS_MAPPINGS.update(PREVIEW_MESH_VTK_BATCH_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(PREVIEW_MESH_VTK_BATCH_DISP)
NODE_CLASS_MAPPINGS.update(PREVIEW_MESH_DUAL_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(PREVIEW_MESH_DUAL_DISP)
NODE_CLASS_MAPPINGS.update(PREVIEW_MESH_UV_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(PREVIEW_MESH_UV_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
