"""
Uv nodes aggregation.
"""

from .xatlas_unwrap import XAtlasUVUnwrapNode, NODE_CLASS_MAPPINGS as XATLAS_UNWRAP_MAPS, NODE_DISPLAY_NAME_MAPPINGS as XATLAS_UNWRAP_DISP
from .libigl_lscm import LibiglLSCMNode, NODE_CLASS_MAPPINGS as LIBIGL_LSCM_MAPS, NODE_DISPLAY_NAME_MAPPINGS as LIBIGL_LSCM_DISP
from .libigl_harmonic import LibiglHarmonicNode, NODE_CLASS_MAPPINGS as LIBIGL_HARMONIC_MAPS, NODE_DISPLAY_NAME_MAPPINGS as LIBIGL_HARMONIC_DISP
from .libigl_arap import LibiglARAPNode, NODE_CLASS_MAPPINGS as LIBIGL_ARAP_MAPS, NODE_DISPLAY_NAME_MAPPINGS as LIBIGL_ARAP_DISP
from .blender_uv import BlenderUVNode, NODE_CLASS_MAPPINGS as BLENDER_UV_MAPS, NODE_DISPLAY_NAME_MAPPINGS as BLENDER_UV_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(XATLAS_UNWRAP_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(XATLAS_UNWRAP_DISP)
NODE_CLASS_MAPPINGS.update(LIBIGL_LSCM_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(LIBIGL_LSCM_DISP)
NODE_CLASS_MAPPINGS.update(LIBIGL_HARMONIC_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(LIBIGL_HARMONIC_DISP)
NODE_CLASS_MAPPINGS.update(LIBIGL_ARAP_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(LIBIGL_ARAP_DISP)
NODE_CLASS_MAPPINGS.update(BLENDER_UV_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(BLENDER_UV_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
